name: static_docs

on:
  push:
    branches:
    - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
        path: repo
    - name: Build HTML for master
      run: | 
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-11-widoco-1.4.17-jar-with-dependencies.jar
           mkdir repo/public 
           java -jar widoco.jar -ontFile repo/GPO.ttl -outFolder repo/public -htaccess -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           cp repo/public/index-en.html repo/public/index.html
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: repo/public # The folder the action should deploy.
        branch: gh-pages # default
